name: Testing Yii2 with MySQL
on: [push, pull_request]
jobs:
  yii:
    name: Yii2 (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-18.04
    env:
      DB_USERNAME: root
      DB_PASSWORD: yii
      TEST_DB_USERNAME: root
      TEST_DB_PASSWORD: yii
      DB_CHARSET: utf8

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: yii
          MYSQL_DATABASE: yii
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-intervals=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-versions ['7.2', '7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hasFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.dist', '.env');"
          php console/yii app/setup
          npm install --development
          npm run build
        env:
          DB_DSN: mysql:host=127.0.0.1;port=${{ job.services.mysql.ports['3306'] }};dbname=yii
          TEST_DB_DSN: mysql:host=127.0.0.1;port=${{ job.services.mysql.ports['3306'] }};dbname=yii

      - name: Run Tests
        run: |
          vendor/bin/codecept build
          php tests/bin/yii app/setup --interactive=0
          nohup php -S localhost:8080 > yii.log 2>&1 &
          vendor/bin/codecept run
        env:
          DB_DSN: mysql:host=127.0.0.1;port=${{ job.services.mysql.ports['3306'] }};dbname=yii
          TEST_DB_DSN: mysql:host=127.0.0.1;port=${{ job.services.mysql.ports['3306'] }};dbname=yii
